Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -50,14 +50,15 @@ jobs:
           # echo "RUN_ID=$RUN_ID" >> $GITHUB_ENV
           # echo "Latest run_id: $RUN_ID"
           
-          # 2. Ambil Run ID dari log menggunakan grep
-          # MLflow biasanya mencetak: "Run with ID 'xxxxxxxxxxxx' completed successfully"
-          # Kita ambil string 32 karakter di dalam tanda petik tersebut
-          RUN_ID=$(grep -oP 'Run with ID \K[a-f0-9]{32}' run_output.txt | head -n 1)
+          # Kita mencari di mlruns/0, membuang 'meta.yaml' dan folder 'models'
+          # head -n 1 akan mengambil folder ID asli yang paling baru
+          RUN_ID=$(ls -t mlruns/0 | grep -vE "meta.yaml|models" | head -n 1)
           
-          if [ -z "$RUN_ID" ]; then
-            echo "Gagal mengambil ID dari log, mencoba cara cadangan via folder..."
-            RUN_ID=$(ls -t mlruns/0 | grep -v "meta.yaml" | head -n 1)
+          # Validasi: Jika ID tetap tidak ditemukan atau aneh, kita hentikan proses
+          if [ -z "$RUN_ID" ] || [ "$RUN_ID" == "models" ]; then
+            echo "Error: Run ID asli tidak ditemukan! Log folder:"
+            ls -R mlruns/0
+            exit 1
           fi
 
           echo "RUN_ID=$RUN_ID" >> $GITHUB_ENV
